PokerProject/Models/Tournament.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PokerProject.Models
{
    public class Tournament
    {
        public int TournamentId { get; set; }
        public string TournamentName { get; set; }
        public DateTime TournamentDate { get; set; }
        public int MinBuyIN { get; set; }
        public int MaxBuyIn { get; set; }
        ICollection<ApplicationUser> Players { get; set; }
    }
}

PokerProject/Controllers/TournamentController.cs
using Microsoft.AspNet.Identity;
using PokerProject.Models;
using PokerProject.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PokerProject.Controllers
{
    public class TournamentController : Controller
    {
        private ApplicationDbContext context;

        public TournamentController()
        {
            context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            context.Dispose();
        }

        // GET: Tournament
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ShowEntriesPerTour()
        {

            var query = from t in context.TournamentEntries
                        group t by t.TournamentId into idgroup
                        select new ShowTourEntries()
                        {
                            TournamentId = idgroup.Key,
                            PlayersCount = idgroup.Count()
                        };


            return View(query.ToList());
        }

        [Authorize]
        public ActionResult JoinTournament(int id)
        {
            var tour = context.Tournaments.SingleOrDefault(t => t.TournamentId == id);
            if (tour == null)
                return HttpNotFound();
            var tournamentEntry = new TournamentJoinViewModel
            {
                Tournament = tour
            };

            return View(tournamentEntry);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Join(TournamentJoinViewModel viewmodel)
        {
            var userId = User.Identity.GetUserId();
            var entry = new TournamentEntry
            {
                TournamentId = viewmodel.Tournament.TournamentId,
                PlayerId = userId,
                PlayerBuyIn = viewmodel.PlayerBuyIn
            };

            context.TournamentEntries.Add(entry);
            context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        public ActionResult ShowTournaments()
        {
            var tournaments = context.Tournaments.ToList();
            return View(tournaments);
        }

        [Authorize]
        public ActionResult DeleteTournament(int id)
        {
            var tour = context.Tournaments.SingleOrDefault(t => t.TournamentId == id);
            if (tour == null)
                return HttpNotFound();

            context.Tournaments.Remove(tour);
            context.SaveChanges();

            return RedirectToAction("ShowTournaments");
        }

        [Authorize]
        public ActionResult EditTournament(int id)
        {
            var tour = context.Tournaments.SingleOrDefault(t => t.TournamentId == id);
            if (tour == null)
                return HttpNotFound();

            return View("EditTournament", tour);
        }

        [Authorize]
        public ActionResult Edit(Tournament tournament)
        {
            var tour = context.Tournaments.SingleOrDefault(t => t.TournamentId == tournament.TournamentId);

            if (tour == null)
                return HttpNotFound();

            tour.TournamentName = tournament.TournamentName;
            tour.TournamentDate = tournament.TournamentDate;
            tour.MaxBuyIn = tournament.MaxBuyIn;
            tour.MinBuyIN = tournament.MinBuyIN;

            context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public ActionResult Tournament()
        {
            return View("CreateTournament");
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateTournament(Tournament tournament)
        {
            if (!ModelState.IsValid)
            {
                //var errors = ModelState.Select(x => x.Value.Errors)
                //           .Where(y => y.Count > 0)
                //           .ToList();

                return View("CreateTournament", tournament); //need validation            
            }


            if (tournament.TournamentId == 0)
                context.Tournaments.Add(tournament);


            context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
    }
}

PokerProject/Views/Tournament/CreateTournament.cshtml
@model PokerProject.Models.Tournament
@{
    ViewBag.Title = "CreateTournament";
}

<h2>CreateTournament</h2>


@using (Html.BeginForm("CreateTournament", "Tournament"))
{

    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    @*@Html.HiddenFor(t => t.TournamentId)*@
    <div class="form-group">
        @Html.LabelFor(t => t.TournamentName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(t => t.TournamentName, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(t => t.TournamentDate, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(t => t.TournamentDate, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(t => t.MaxBuyIn, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(t => t.MaxBuyIn, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(t => t.MinBuyIN, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(t => t.MinBuyIN, new { @class = "form-control" })
        </div>
    </div>


    <button type="submit" class="btn btn bg-primary">Create</button>
}

PokerProject/Views/Tournament/EditTournament.cshtml
@model PokerProject.Models.Tournament
@{
    ViewBag.Title = "EditTournament";
}

<h2>EditTournament</h2>

@using (Html.BeginForm("Edit", "Tournament"))
{

    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    @Html.HiddenFor(t => t.TournamentId)
    <div class="form-group">
        @Html.LabelFor(t => t.TournamentName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(t => t.TournamentName, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(t => t.TournamentDate, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(t => t.TournamentDate, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(t => t.MaxBuyIn, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(t => t.MaxBuyIn, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(t => t.MinBuyIN, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(t => t.MinBuyIN, new { @class = "form-control" })
        </div>
    </div>


    <button type="submit" class="btn btn bg-primary">Create</button>
}

PokerProject/Views/Tournament/JoinTournament.cshtml
@model PokerProject.ViewModels.TournamentJoinViewModel
@{
    ViewBag.Title = "JoinTournament";
}

<h2>Tournament Info</h2>
<p>Please, fill your buy in!</p>



@using (Html.BeginForm("Join", "Tournament"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(t => t.Tournament.TournamentId)
    <div class="form-group">
        @Html.LabelFor(t => t.Tournament.TournamentName)
        @Html.TextBoxFor(t => t.Tournament.TournamentName, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(t => t.Tournament.TournamentDate)
        @Html.TextBoxFor(t => t.Tournament.TournamentDate, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(t => t.Tournament.MaxBuyIn)
        @Html.TextBoxFor(t => t.Tournament.MaxBuyIn, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(t => t.Tournament.MinBuyIN)
        @Html.TextBoxFor(t => t.Tournament.MinBuyIN, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(t => t.PlayerBuyIn)
        @Html.TextBoxFor(t => t.PlayerBuyIn, new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
}

PokerProject/Views/Tournament/ShowEntriesPerTour.cshtml
@model IEnumerable<PokerProject.ViewModels.ShowTourEntries>
@{
    ViewBag.Title = "ShowEntriesPerTour";
}

    <table class="table table-bordered">

        <tr>
            <th>TournamentId</th>
            <th>Number of players</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelitem => item.TournamentId)</td>
                <td>@item.PlayersCount</td>
            </tr>
        }

    </table>

PokerProject/Views/Tournament/ShowTournaments.cshtml
@model IEnumerable<PokerProject.Models.Tournament>
@{
    ViewBag.Title = "ShowTournaments";
}

<h2>Tournaments</h2>
<p>
    @Html.ActionLink("New Tournament", "Tournament", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("Players Per Tour", "ShowEntriesPerTour", null, new { @class = "btn btn-primary" })
</p>
<ul>
    @foreach (var tournament in Model)
    {
        <li>
            <div>
                <h4>@tournament.TournamentName</h4>
                <span>@tournament.TournamentDate.ToString("MMM/dd/yyy")</span>
                <span>@tournament.MaxBuyIn</span>
                <span>@tournament.MinBuyIN</span>
                @Html.ActionLink("Edit", "EditTournament", new { id = tournament.TournamentId })
                @Html.ActionLink("Delete", "DeleteTournament", new { id = tournament.TournamentId })
                @Html.ActionLink("Join", "JoinTournament", new { id = tournament.TournamentId })
            </div>
        </li>
    }
</ul>